<a href="https://colab.research.google.com/github/zeer0e1/pandas-descomplicado/blob/main/Curso_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Curso de pandas - IA Expert Academy


## Instalação do Pandas

In [65]:
!pip install pandas

In [66]:
import pandas as pd
import numpy as np
print(np.__version__)

1.23.5


## Series

In [67]:
serie_dados = pd.Series([10,20,30,40,50])
print(serie_dados)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [68]:
type(serie_dados)

pandas.core.series.Series

In [69]:
array_inteiros = [10,20,30,40,50]
indices = ['A','B','C','D','E']
series_dados = pd.Series(array_inteiros, index=indices)
print(series_dados)

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [70]:
np_array_inteiros = np.array([10,20,30,40,50])
print(np_array_inteiros)
type(np_array_inteiros)

[10 20 30 40 50]


numpy.ndarray

In [71]:
series = pd.Series(np_array_inteiros)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [72]:
series.ndim

1

In [73]:
series.size

5

In [74]:
series.index = ['X','Z','V','Y','W']
print(series)

X    10
Z    20
V    30
Y    40
W    50
dtype: int64


In [75]:
valores = np.random.random(10)
index = np.arange(0,10)
print(valores)
print(index)

[0.28493071 0.94921481 0.31473797 0.84724039 0.65361091 0.05602048
 0.32953979 0.0036123  0.43265541 0.01001166]
[0 1 2 3 4 5 6 7 8 9]


In [76]:
type(valores),type(index)

(numpy.ndarray, numpy.ndarray)

In [77]:
serie_dados = pd.Series(valores,index)
print(serie_dados)

0    0.284931
1    0.949215
2    0.314738
3    0.847240
4    0.653611
5    0.056020
6    0.329540
7    0.003612
8    0.432655
9    0.010012
dtype: float64


In [78]:
dicionario = {'Joao':10,'alice':5,'Gustavo':6,'Pedro':9}
type(dicionario)

dict

In [79]:
dicionario

{'Joao': 10, 'alice': 5, 'Gustavo': 6, 'Pedro': 9}

In [80]:
dict_serie_dados = pd.Series(dicionario)
print(dict_serie_dados)

Joao       10
alice       5
Gustavo     6
Pedro       9
dtype: int64


## Fatiamento (slicing)

In [81]:
serie_dados[:]

0    0.284931
1    0.949215
2    0.314738
3    0.847240
4    0.653611
5    0.056020
6    0.329540
7    0.003612
8    0.432655
9    0.010012
dtype: float64

In [82]:
serie_dados[0:3]

0    0.284931
1    0.949215
2    0.314738
dtype: float64

In [83]:
serie_dados[:4]

0    0.284931
1    0.949215
2    0.314738
3    0.847240
dtype: float64

In [84]:
serie_dados[-1:]

9    0.010012
dtype: float64

In [85]:
serie_dados[:-1]

0    0.284931
1    0.949215
2    0.314738
3    0.847240
4    0.653611
5    0.056020
6    0.329540
7    0.003612
8    0.432655
dtype: float64

## Cópia, conversão e concactenação

In [86]:
serie_dados2 = serie_dados.copy()

In [87]:
serie_dados2.dtype

dtype('float64')

In [88]:
s3 = serie_dados2.astype(int)

In [89]:
s3.dtype

dtype('int64')

In [90]:
dados_novos = {'lucas':30,'rau':28}
serie_dados3 = pd.Series(dados_novos)
serie_dados3

lucas    30
rau      28
dtype: int64

In [91]:
dict_serie_dados

Joao       10
alice       5
Gustavo     6
Pedro       9
dtype: int64

In [92]:
serie_dados4 = pd.concat([dict_serie_dados, serie_dados3])
serie_dados4

Joao       10
alice       5
Gustavo     6
Pedro       9
lucas      30
rau        28
dtype: int64

# Acessando aos dados com iloc


*   Acessando elemento pelo indice



In [93]:
dataset = pd.read_csv('census.csv')

In [ ]:
dataset

In [95]:
serie_idade = dataset['age']
serie_idade
type(serie_idade)
dataset['age'].values

array([39, 50, 38, ..., 58, 22, 52])

In [ ]:
serie_idade.head(20)

In [ ]:
serie_idade.tail(20)

In [98]:
serie_idade.iloc[0]

39

In [99]:
serie_idade.iloc[32551]

32

In [100]:
serie_idade.iloc[-1]

52

In [101]:
serie_idade.iloc[[0,2,4]]

0    39
2    38
4    28
Name: age, dtype: int64

In [102]:
lista_idade = []
for i in serie_idade.items():
    if i[1] > 50:
        lista_idade.append(i[1])


In [103]:
print(lista_idade)

[53, 52, 54, 59, 56, 54, 53, 57, 53, 53, 79, 67, 52, 59, 53, 57, 76, 56, 53, 56, 55, 61, 70, 64, 52, 71, 68, 66, 51, 53, 58, 51, 58, 60, 54, 64, 90, 54, 53, 60, 66, 75, 65, 59, 56, 58, 59, 58, 59, 64, 61, 60, 57, 65, 55, 77, 62, 76, 63, 58, 66, 55, 53, 67, 56, 59, 65, 62, 56, 57, 54, 52, 52, 63, 80, 51, 60, 54, 52, 60, 67, 52, 63, 59, 72, 62, 52, 58, 53, 57, 74, 67, 57, 58, 72, 69, 54, 52, 51, 58, 65, 57, 59, 52, 57, 55, 60, 60, 51, 52, 52, 65, 58, 52, 60, 71, 58, 70, 58, 66, 54, 60, 65, 55, 56, 55, 55, 58, 54, 59, 53, 51, 55, 54, 61, 59, 60, 61, 68, 64, 56, 64, 57, 62, 53, 73, 72, 55, 63, 51, 62, 55, 61, 59, 71, 51, 55, 63, 54, 63, 51, 53, 53, 67, 81, 64, 51, 51, 54, 51, 51, 55, 67, 78, 60, 63, 51, 56, 58, 66, 54, 51, 51, 56, 76, 66, 90, 64, 61, 53, 52, 61, 54, 58, 62, 68, 69, 60, 58, 53, 63, 59, 56, 61, 51, 51, 54, 65, 88, 51, 58, 51, 59, 65, 51, 51, 59, 61, 61, 54, 63, 53, 55, 75, 52, 55, 65, 62, 54, 51, 52, 57, 53, 69, 73, 51, 67, 52, 65, 57, 58, 63, 58, 51, 61, 55, 52, 57, 51, 71,

In [104]:
serie_idade.iloc[lista_idade]

53    50
52    47
54    47
59    30
56    46
      ..
72    29
65    36
53    50
58    41
52    47
Name: age, Length: 6460, dtype: int64

# Acesso aos dados com loc


*   Acessar elementos por "string"



In [ ]:
!pip install Faker

In [106]:
from faker import Faker
fake = Faker()

In [107]:
fake.name()

'David Smith'

In [108]:
indices_nome = []
for _ in range(32561):
    indices_nome.append(fake.name())

In [109]:
type(indices_nome), len(indices_nome)

(list, 32561)

In [ ]:
indices_nome[0:10]

In [ ]:
serie_idade.size

In [ ]:
serie_idade_nome = pd.Series(np.array(dataset['age']), index= indices_nome)
serie_idade_nome

In [115]:
serie_idade_nome = serie_idade_nome.drop_duplicates()

In [ ]:
serie_idade_nome.loc[['Debra Holland','Ray Moore']]

In [ ]:
serie_idade_nome3 = serie_idade_nome.copy()
serie_idade_nome3

In [ ]:
serie_idade_nome3.reset_index(drop=True)

# Ordenação

In [ ]:
serie_idade_nome.sort_values()

In [ ]:
serie_idade_nome.sort_values(ascending = False)

In [ ]:
serie_idade_nome.sort_index(ascending = True)

In [ ]:
sr = serie_idade_nome.sort_values(ascending=  False).iloc[0:11]
print(sr)

# Contagem

In [134]:
serie_idade_nome.size

73

In [ ]:
serie_idade_nome

In [ ]:
serie_idade_nome.value_counts(normalize = True, sort=True)

In [ ]:
serie_idade_nome.value_counts(bins = 10)

# Filtragem

In [142]:
fake.country()

'Saudi Arabia'

In [143]:
indices_pais = []
for _ in range(serie_idade_nome.size):
    indices_pais.append(fake.country())

In [ ]:
indices_pais[0:11]

In [146]:
series_pais = pd.Series(np.array(dataset['age']), index= indices_pais)

In [ ]:
series_pais

In [ ]:
series_pais.loc[series_pais > 50]

In [ ]:
series_pais.loc[(series_pais > 50) & (series_pais.index == "India")]

In [152]:
series_pais.index.isin(['India','Brasil'])

array([False, False, False, ..., False, False, False])

In [154]:
~series_pais.index.isin(['India','Brasil'])

array([ True,  True,  True, ...,  True,  True,  True])

# Operações matemáticas

In [156]:
series_pais

Kiribati      39
Kenya         50
Guinea        38
Algeria       53
Canada        28
              ..
Canada        27
Congo         40
Montserrat    58
Sudan         22
Bolivia       52
Length: 32561, dtype: int64

In [157]:
series_pais + 2

Kiribati      41
Kenya         52
Guinea        40
Algeria       55
Canada        30
              ..
Canada        29
Congo         42
Montserrat    60
Sudan         24
Bolivia       54
Length: 32561, dtype: int64

In [158]:
series_pais.add(2)

Kiribati      41
Kenya         52
Guinea        40
Algeria       55
Canada        30
              ..
Canada        29
Congo         42
Montserrat    60
Sudan         24
Bolivia       54
Length: 32561, dtype: int64

In [159]:
series_pais.sub(2)

Kiribati      37
Kenya         48
Guinea        36
Algeria       51
Canada        26
              ..
Canada        25
Congo         38
Montserrat    56
Sudan         20
Bolivia       50
Length: 32561, dtype: int64

In [160]:
series_pais - 2

Kiribati      37
Kenya         48
Guinea        36
Algeria       51
Canada        26
              ..
Canada        25
Congo         38
Montserrat    56
Sudan         20
Bolivia       50
Length: 32561, dtype: int64

In [161]:
series_pais.mul(2)

Kiribati       78
Kenya         100
Guinea         76
Algeria       106
Canada         56
             ... 
Canada         54
Congo          80
Montserrat    116
Sudan          44
Bolivia       104
Length: 32561, dtype: int64

In [162]:
series_pais.div(2)

Kiribati      19.5
Kenya         25.0
Guinea        19.0
Algeria       26.5
Canada        14.0
              ... 
Canada        13.5
Congo         20.0
Montserrat    29.0
Sudan         11.0
Bolivia       26.0
Length: 32561, dtype: float64

In [ ]:
s1 = pd.Series([20,30,40])
s2 = pd.Series([1,2,3])
s1, s2

In [166]:
s1.add(s2)

0    21
1    32
2    43
dtype: int64

In [167]:
s1.sub(s2)

0    19
1    28
2    37
dtype: int64

In [168]:
s1.mul(s2)

0     20
1     60
2    120
dtype: int64

In [169]:
s1.div(s2)

0    20.000000
1    15.000000
2    13.333333
dtype: float64

# Operações com Strings

In [170]:
series_pais

Kiribati      39
Kenya         50
Guinea        38
Algeria       53
Canada        28
              ..
Canada        27
Congo         40
Montserrat    58
Sudan         22
Bolivia       52
Length: 32561, dtype: int64

In [178]:
serie_pais_index = series_pais.index.to_series()

In [182]:
serie_pais_index.reset_index(drop = True, inplace = True)
serie_pais_index

0          Kiribati
1             Kenya
2            Guinea
3           Algeria
4            Canada
            ...    
32556        Canada
32557         Congo
32558    Montserrat
32559         Sudan
32560       Bolivia
Length: 32561, dtype: object

In [184]:
serie_pais_index.str.contains("tse")

0        False
1        False
2        False
3        False
4        False
         ...  
32556    False
32557    False
32558     True
32559    False
32560    False
Length: 32561, dtype: bool

In [186]:
serie_pais_index.str.upper()
serie_pais_index.str.lower()

0          kiribati
1             kenya
2            guinea
3           algeria
4            canada
            ...    
32556        canada
32557         congo
32558    montserrat
32559         sudan
32560       bolivia
Length: 32561, dtype: object

In [187]:
serie_pais_index.str.strip("ken")

0          Kiribati
1             Kenya
2            Guinea
3           Algeria
4            Canada
            ...    
32556        Canada
32557         Congo
32558    Montserrat
32559          Suda
32560       Bolivia
Length: 32561, dtype: object

In [189]:
serie_pais_index.str.split(' ',expand = True)

0     1     2     3     4     5     6     7
0        Kiribati  None  None  None  None  None  None  None
1           Kenya  None  None  None  None  None  None  None
2          Guinea  None  None  None  None  None  None  None
3         Algeria  None  None  None  None  None  None  None
4          Canada  None  None  None  None  None  None  None
...           ...   ...   ...   ...   ...   ...   ...   ...
32556      Canada  None  None  None  None  None  None  None
32557       Congo  None  None  None  None  None  None  None
32558  Montserrat  None  None  None  None  None  None  None
32559       Sudan  None  None  None  None  None  None  None
32560     Bolivia  None  None  None  None  None  None  None

[32561 rows x 8 columns]